module.exports = {
  parser: 'babel-eslint',
  env: {
    es6: true,
    node: true,
    browser: true,
    jest: true,
    mocha: true,
  },
  plugins: ['flowtype', 'import', 'babel', 'fp', 'eslint-comments'],
  extends: [
    'eslint:recommended',
    'plugin:import/recommended',
    'plugin:eslint-comments/recommended',
  ],
  parserOptions: {
    ecmaVersion: 7,
    sourceType: 'module',
    ecmaFeatures: {
      experimentalObjectRestSpread: true,
      jsx: true,
    },
  },
  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: true,
    },
  },
  rules: {
    'accessor-pairs': 'error',
    'array-bracket-spacing': 'error',
    'array-callback-return': 'error',
    'arrow-body-style': 'error',
    'arrow-parens': 0,
    'arrow-spacing': [
      'error',
      {
        after: true,
        before: true,
      },
    ],
    'block-scoped-var': 'error',
    'callback-return': 'error',
    camelcase: 1,
    'comma-dangle': 0,
    'comma-spacing': [
      'error',
      {
        after: true,
        before: false,
      },
    ],
    'comma-style': ['error', 'last'],
    complexity: 'error',
    'computed-property-spacing': 'error',
    'consistent-return': 'error',
    'consistent-this': 'error',
    'default-case': 'error',
    'dot-notation': 'error',
    'eol-last': 'error',
    eqeqeq: 1,
    'func-call-spacing': 'error',
    'func-name-matching': 'error',
    'func-names': 'error',
    'func-style': 0,
    'generator-star-spacing': 'error',
    'guard-for-in': 'error',
    'handle-callback-err': 'error',
    'id-blacklist': 'error',
    'id-length': 0,
    'id-match': 'error',
    indent: 'off',
    'jsx-quotes': 'error',
    'key-spacing': 'error',
    'keyword-spacing': [
      'error',
      {
        after: true,
        before: true,
      },
    ],
    'linebreak-style': ['error', 'unix'],
    'lines-around-comment': 'error',
    'lines-around-directive': 'error',
    'max-depth': 'error',
    'max-len': [
      1,
      {
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
      },
    ],
    'max-nested-callbacks': 'error',
    'max-statements-per-line': 'error',
    'new-parens': 'error',
    'newline-after-var': 0,
    'no-alert': 'error',
    'no-array-constructor': 'error',
    'no-await-in-loop': 'error',
    'no-bitwise': 'error',
    'no-caller': 1,
    'no-catch-shadow': 1,
    'no-console': 0,
    'no-continue': 'error',
    'no-div-regex': 'error',
    'no-duplicate-imports': 'error',
    'no-empty-function': 'error',
    'no-eq-null': 1,
    'no-eval': 'error',
    'no-extend-native': 1,
    'no-extra-bind': 1,
    'no-extra-label': 'error',
    'no-floating-decimal': 1,
    'no-implicit-coercion': 1,
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-inline-comments': 'off',
    'no-invalid-this': 0,
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-loop-func': 2,
    'no-mixed-operators': 0,
    'no-mixed-requires': 'error',
    'no-multi-assign': 'error',
    'no-multi-spaces': 1,
    'no-multi-str': 'error',
    'no-multiple-empty-lines': 1,
    'no-native-reassign': 'error',
    'no-negated-condition': 'error',
    'no-negated-in-lhs': 'error',
    'no-new': 2,
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-wrappers': 1,
    'no-octal-escape': 'error',
    'no-param-reassign': 1,
    'no-path-concat': 'error',
    'no-plusplus': 'error',
    'no-process-env': 0,
    'no-process-exit': 'error',
    'no-proto': 'error',
    'no-prototype-builtins': 'error',
    'no-restricted-globals': 'error',
    'no-restricted-imports': 'error',
    'no-restricted-modules': 'error',
    'no-restricted-properties': 'error',
    'no-restricted-syntax': 'error',
    'no-return-assign': 1,
    'no-return-await': 1,
    'no-script-url': 'error',
    'no-self-compare': 1,
    'no-sequences': 1,
    'no-shadow': 'error',
    'no-shadow-restricted-names': 1,
    'no-spaced-func': 'error',
    'no-sync': 'error',
    'no-tabs': 'error',
    'no-template-curly-in-string': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 1,
    'no-undef-init': 'error',
    'no-undefined': 1,
    'no-unmodified-loop-condition': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': [
      1,
      {
        allowShortCircuit: true,
      },
    ],
    'no-unused-vars': 1,
    'no-use-before-define': [1, 'nofunc'],
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 1,
    'no-useless-escape': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 1,
    'no-whitespace-before-property': 'error',
    'no-with': 'error',
    'object-shorthand': 'error',
    'one-var': [1, 'never'],
    'one-var-declaration-per-line': 'error',
    'operator-assignment': 'error',
    'padded-blocks': 'off',
    'prefer-arrow-callback': 'error',
    'prefer-const': 1,
    'prefer-destructuring': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-promise-reject-errors': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'quote-props': 'off',
    quotes: [
      'error',
      'single',
      {
        avoidEscape: true,
      },
    ],
    radix: 1,
    'require-await': 1,
    'require-jsdoc': 'off',
    'rest-spread-spacing': 'error',
    semi: 'off',
    'semi-spacing': 'error',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'sort-vars': 'error',
    'space-before-blocks': 'error',
    'space-before-function-paren': 'off',
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'space-unary-ops': 'error',
    'spaced-comment': 'off',
    strict: 'error',
    'symbol-description': 'error',
    'template-curly-spacing': 'error',
    'unicode-bom': ['error', 'never'],
    'valid-jsdoc': [
      1,
      {
        requireReturnDescription: false,
      },
    ],
    'vars-on-top': 'error',
    'wrap-regex': 0,
    'yield-star-spacing': 'error',
    'flowtype/define-flow-type': 1,
    'flowtype/require-valid-file-annotation': 1,
    'flowtype/use-flow-type': 1,
    'flowtype/valid-syntax': 1,
    'import/unambiguous': 0,
    'import/no-extraneous-dependencies': 1,
    'import/no-mutable-exports': 1,
    'import/order': 1,
    'import/newline-after-import': 1,
    'import/prefer-default-export': 0,
    'babel/no-invalid-this': 'error',
    'fp/no-arguments': 1,
    'fp/no-delete': 1,
    'fp/no-events': 1,
    'fp/no-get-set': 1,
    'fp/no-let': 1,
    'fp/no-loops': 1,
    'fp/no-mutating-assign': 1,
    'fp/no-mutating-methods': 0,
    'fp/no-mutation': [
      1,
      {
        commonjs: true,
        allowThis: true,
        // "exceptions": []
      },
    ],
    'fp/no-nil': 0,
    'fp/no-proxy': 1,
    'fp/no-rest-parameters': 0,
    'fp/no-this': 0,
    'fp/no-throw': 0,
    'fp/no-unused-expression': 0,
    'fp/no-valueof-field': 1,
  },
}
